world:
  world_height: 10
  world_width: 10
  step_time: 0.1
  xy_resolution: 0.01 # meter
  yaw_resolution: 5 # degree
  # world_map: 'map_100_100.png'

robots:
  number: 1
  robot_mode: 'diff'  # omni or diff
  init_mode: 0 # 0 custom, 1 single row, 2, random, 3 circle
  init_state_list: [[1, 1, 0], [6, 3, 0]]
  goal_list: [[6, 7, 0], [5, 4, 0]]
  radius_list: [0.2, 0.2]
  vel_max: [1.5, 1.5]
  radius_exp: 0.1

obs_cirs:
  number: 2
  obs_cir_mode: 0
  obs_model: 'static' # static, dynamic
  obs_state_list: [[3, 4], [5, 6]]
  obs_radius_list: [0.2, 0.5]

obs_lines:
  obs_line_states: [[4, 5, 7, 4], [7, 3, 2, 8]]

sensor: 
  type: 'lidar2d'
  robot_id: 0
  ins_pos: [0, 0, 0]
  range_min: 0
  range_max: 10
  angle_min: 0 
  angle_max: 3.1415926
  angle_inc: 0.0873
  scan_time: 0.1
  noise=True: 
  std: 0.2
  
  
  
  
